Repository pocketsizefund/pocketsizefund, pull requests merged in 2024-07, with the labels that each got.

#273 Update README content and links
  README.md
  libraries/python/pocketsizefund/config/config.py
  libraries/python/pocketsizefund/model/model.py
  pkg/pocketsizefund/config/api_check.py
  platform/positionmanager/entrypoint.py
  platform/pricemodel/entrypoint.py
Labels: feature

#288 cleanup some linting errors
  .github/workflows/python.yml
  libraries/python/pocketsizefund/model/model.py
  libraries/python/tests/test_api_key_required.py
  pipelines/filings/config.py
  platform/positionmanager/entrypoint.py
  platform/positionmanager/event_bus.py
Labels: bug, python

#289 Deprecate unused trade methods/add "baseline buy" method
  libraries/python/pocketsizefund/config/config.py
  libraries/python/pocketsizefund/trade/trade.py
  libraries/python/tests/test_trade.py
  platform/positionmanager/entrypoint.py
Labels: feature, python

#283 create shell rust libary
  .gitignore
  .mise/tasks/libraries/rust/build
  .mise/tasks/libraries/rust/publish
  .mise/tasks/libraries/rust/test
  libraries/rust/Cargo.lock
  libraries/rust/Cargo.toml
  libraries/rust/deny.toml
  libraries/rust/src/lib.rs
  libraries/rust/src/polygon.rs
  libraries/rust/src/schema/asset_class.rs
  libraries/rust/src/schema/exchange.rs
  libraries/rust/src/schema/locale.rs
  libraries/rust/src/schema/mod.rs
  libraries/rust/src/schema/ticker.rs
Labels: type-feature, language-rust

#284 working on rust lib
  .gitignore
  .mise.toml
  .mise/config.toml
  .mise/tasks/libraries/rust/build
  .mise/tasks/repo/lint
  libraries/rust/Cargo.lock
  libraries/rust/Cargo.toml
  libraries/rust/src/lib.rs
  libraries/rust/src/logger.rs
  libraries/rust/src/schema/exchange.rs
  libraries/rust/src/schema/market/holidays.rs
  libraries/rust/src/schema/market/mod.rs
  libraries/rust/src/schema/market/status.rs
  libraries/rust/src/schema/mod.rs
  libraries/rust/src/schema/prelude.rs
  libraries/rust/src/schema/symbol.rs
  libraries/rust/src/schema/ticker.rs
  platform/discord/Cargo.
Labels: type-feature

#290 gitignore all rust targets
  .gitignore
Labels: type-meta

#294 Minor updates to the main README
  .github/workflows/python.yml
  .github/workflows/repo.yaml
  .github/workflows/rust.yml
  README.md
Labels: type-meta

#286 Create initial Rust pubsub library
  .gitignore
  Cargo.lock
  Cargo.toml
  libraries/python/pocketsizefund/event/__init__.py
  libraries/python/pocketsizefund/event/event.py
  libraries/python/poetry.lock
  libraries/python/pyproject.toml
  libraries/python/tests/test_config.py
  libraries/python/tests/test_data.py
  libraries/python/tests/test_event.py
  libraries/python/tests/test_storage.py
  libraries/python/tests/test_trade.py
  libraries/rust/src/event/mod.rs
  libraries/rust/src/event/publisher.rs
  libraries/rust/src/event/subscriber.rs
  libraries/rust/src/lib.rs
  poetry.lock
  pyproject.toml
Labels: type-feature
