Repository pocketsizefund/pocketsizefund, pull requests merged in 2025-05, with the labels that each got.

#508 Update GitHub Python workflow configurations
  .flox/env/manifest.toml
  .github/workflows/quality.yaml
  .github/workflows/test.yaml
  README.md
Labels: bug

#517 Remove parallel mode from Coveralls check
  .github/workflows/test.yaml
Labels: bug

#525 Fix duplicated word in CLAUDE instructions
  CLAUDE.md
Labels: codex

#528 Fix Cloud Run cron job schedule
  infrastructure/cloud_run.py
Labels: codex

#533 Switch CI from uv to flox
  .github/workflows/quality.yaml
  .github/workflows/test.yaml
Labels: codex

#532 Add deployment workflow
  .github/workflows/deploy.yaml
  .mise.toml
Labels: codex

#527 Add OS matrix to CI
  .github/workflows/quality.yaml
  .github/workflows/test.yaml
Labels: codex

#524 Fix GitHub spelling in CLAUDE instructions
  CLAUDE.md
Labels: codex

#523 Build initial positionmanager service
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/PULL_REQUEST_TEMPLATE.md
  application/datamanager/pyproject.toml
  application/datamanager/tests/test_datamanager_main.py
  application/positionmanager/Dockerfile
  application/positionmanager/pyproject.toml
  application/positionmanager/src/positionmanager/__init__.py
  application/positionmanager/src/positionmanager/clients.py
  application/positionmanager/src/positionmanager/main.py
  application/positionmanager/src/positionmanager/models.py
  application/positionmanager/src/positionmanager/portfolio.py
  application/positionmanager/tests/test_positionmanager_main.py
  pyproject.toml
  uv.lock
Labels: application, python, feature

#530 Add prod bucket
  infrastructure/__main__.py
  infrastructure/buckets.py
  infrastructure/cloud_run.py
Labels: codex

#541 Add account API feature test
  application/accountmanager/features/account.feature
Labels: codex

#545 Add Codex instructions
  AGENTS.md
Labels: codex

#549 Fix AGENTS instructions
  AGENTS.md
Labels: codex

#551 Fix datamanager Dockerfile and improve error handling
  .flox/env/manifest.lock
  .github/workflows/test.yaml
  .gitignore
  .mise.toml
  AGENTS.md
  Dockerfile.test
  application/datamanager/Dockerfile
  application/datamanager/features/steps/equity_bars_steps.py
  application/datamanager/features/steps/health_steps.py
  application/datamanager/pyproject.toml
  application/datamanager/src/datamanager/bars.sql
  application/datamanager/src/datamanager/config.py
  application/datamanager/src/datamanager/main.py
  application/datamanager/src/datamanager/query.py
  application/positionmanager/Dockerfile
  compose.yaml
  infrastructure/cloud_run.py
  pyproject.toml
  uv.lock
  workflows/prediction_model.py
Labels: codex

#547 Update Pulumi infrastructure to build Docker images
  .gitignore
  .mise.toml
  application/datamanager/Dockerfile.test
  application/datamanager/compose.yaml
  application/datamanager/features/environment.py
  application/datamanager/features/equity_bars.feature
  application/datamanager/features/health.feature
  application/datamanager/features/steps/equity_bars_steps.py
  application/datamanager/features/steps/health_steps.py
  application/datamanager/mise.toml
  application/datamanager/pyproject.toml
  application/datamanager/src/datamanager/config.py
  application/datamanager/src/datamanager/main.py
  application/datamanager/src/datamanager/models.py
  application/datamanager/tests/test_datamanager_main.py
  infrastructure/Pulumi.yaml
  infrastructure/buckets.py
  infrastructure/cloud_run.py
  infrastructure/main.py
  infrastructure/pyproject.toml
  pyproject.toml
  uv.lock
  workflows/__init__.py
  workflows/backfill_datamanager.py
  workflows/pyproject.toml
Labels: codex

#558 Various fixes and cleanups
  .flox/env/manifest.toml
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/workflows/deploy.yaml
  .github/workflows/quality.yaml
  .mise.toml
  AGENTS.md
  CLAUDE.md
  application/datamanager/compose.yaml
  application/datamanager/features/environment.py
  application/datamanager/features/steps/health_steps.py
  application/datamanager/mise.toml
  application/datamanager/pyproject.toml
  application/datamanager/src/datamanager/main.py
  application/positionmanager/pyproject.toml
  compose.yaml
  pyproject.toml
  uv.lock
  workflows/pyproject.toml
Labels: application, python, bug

#559 Build initial prediction engine service
  .dockerignore
  .github/workflows/test.yaml
  .gitignore
  .mise.toml
  Dockerfile.test
  application/datamanager/Dockerfile
  application/datamanager/pyproject.toml
  application/datamanager/src/datamanager/config.py
  application/positionmanager/Dockerfile
  application/positionmanager/src/positionmanager/clients.py
  application/positionmanager/src/positionmanager/main.py
  application/predictionengine/Dockerfile
  application/predictionengine/pyproject.toml
  application/predictionengine/src/predictionengine/dataset.py
  application/predictionengine/src/predictionengine/gated_residual_network.py
  application/predictionengine/src/predictionengine/long_short_term_memory.py
  application/predictionengine/src/predictionengine/loss_function.py
  application/predictionengine/src/predictionengine/main.py
  application/predictionengine/src/predictionengine/miniature_temporal_fusion_transformer.py
  application/predictionengine/src/predictionengine/models.py
  application/predictionengine/src/predictionengine/multi_head_self_attention.py
  application/predictionengine/src/predictionengine/post_processor.py
  application/predictionengine/src/predictionengine/ticker_embedding.py
  application/predictionengine/tests/test_dataset.py
  application/predictionengine/tests/test_gated_residual_network.py
  application/predictionengine/tests/test_long_short_term_memory.py
  application/predictionengine/tests/test_loss_function.py
  application/predictionengine/tests/test_multi_head_self_attention.py
  application/predictionengine/tests/test_post_processor.py
  application/predictionengine/tests/test_ticker_embedding.py
  compose.yaml
  infrastructure/cloud_run.py
  pyproject.toml
  todos.md
  uv.lock
  workflows/prediction_model.py
Labels: application, model, python, feature

#577 Add infrastructure for new services
  infrastructure/cloud_run.py
  infrastructure/images.py
  infrastructure/prometheus.yaml
Labels: codex
